<a href="https://colab.research.google.com/github/va4756/algio_sklearn/blob/main/bigdata_sinagong_part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# p8_type1 (제 8회 시험)

## I.작업형1 유형

### 문1-1) 대륙별 맥주 소비량의 평균을 구하여, 가장 많이 소비하는 대륙을 찾으시오.

In [7]:
import pandas as pd
# df = pd.read_csv("drinks.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/drinks.csv")
print(df.shape)
df.head()

(193, 6)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       193 non-null    object
 1   beer_servings                 193 non-null    int64
 2   spirit_servings               193 non-null    int64
 3   wine_servings                 193 non-null    int64
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     193 non-null    object
dtypes: float64(1), int64(3), object(2)
memory usage: 9.2+ KB

In [9]:
continent = df.groupby('continent')['beer_servings'].mean()
continent

continent
Africa            61.471698
Asia              37.045455
Europe           193.777778
North America    145.434783
Oceania           89.687500
South America    175.083333
Name: beer_servings, dtype: float64

In [10]:
top_continent = continent.idxmax()
top_continent

'Europe'

### 문1-2) 최대소비 대륙에서의 국가별 맥주 소비량을 구하시오(5번째 국가의 소비량을 찾으시오).

In [13]:
cond = df['continent'] == top_continent
df = df[cond]
df = df.sort_values('beer_servings', ascending=False)
df
#df.iloc[4]['beer_servings']

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
45,Czech Republic,361,170,134,11.8,Europe
65,Germany,346,117,175,11.3,Europe
135,Poland,343,215,56,10.9,Europe
98,Lithuania,343,244,56,12.9,Europe
81,Ireland,313,118,165,11.4,Europe
140,Romania,297,122,167,10.4,Europe
16,Belgium,295,84,212,10.5,Europe
160,Spain,284,157,112,10.0,Europe
151,Serbia,283,131,127,9.6,Europe
93,Latvia,281,216,62,10.5,Europe
9,Austria,279,75,191,9.7,Europe
156,Slovenia,270,51,276,10.6,Europe
60,Finland,263,133,97,10.0,Europe
120,Netherlands,251,88,190,9.4,Europe
3,Andorra,245,138,312,12.4,Europe
99,Luxembourg,236,133,271,11.4,Europe
75,Hungary,234,215,185,11.3,Europe
76,Iceland,233,61,78,6.6,Europe
25,Bulgaria,231,252,94,10.3,Europe
42,Croatia,230,87,254,10.2,Europe
48,Denmark,224,81,278,10.4,Europe
57,Estonia,224,194,59,9.5,Europe
182,United Kingdom,219,126,195,10.4,Europe
180,Ukraine,206,237,45,8.9,Europe
155,Slovakia,196,293,116,11.4,Europe
136,Portugal,194,67,339,11.0,Europe
44,Cyprus,192,154,113,8.2,Europe
166,Switzerland,185,100,280,10.2,Europe
126,Norway,169,71,129,6.7,Europe
165,Sweden,152,60,186,7.2,Europe
105,Malta,149,100,120,6.6,Europe
15,Belarus,142,373,42,14.4,Europe
67,Greece,133,112,218,8.3,Europe
61,France,127,151,370,11.8,Europe
139,Moldova,109,226,18,6.3,Europe
170,Macedonia,106,27,86,3.9,Europe
1,Albania,89,132,54,4.9,Europe
83,Italy,85,42,237,6.5,Europe
21,Bosnia-Herzegovina,76,173,8,4.6,Europe
64,Georgia,52,100,149,5.4,Europe
113,Montenegro,31,114,128,4.9,Europe
10,Azerbaijan,21,46,5,1.3,Europe
7,Armenia,21,179,11,3.8,Europe
147,San Marino,0,0,0,0.0,Europe
111,Monaco,0,0,0,0.0,Europe

### 문2-1) 방문객 합계와 관광개의 비율을 계산하시오.

In [14]:
import pandas as pd
# df = pd.read_csv("tourist.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/tourist.csv")
print(df.shape)
df.head()

(100, 5)

    나라    관광   공무   사업   기타
0  국가1  1184  270  380   55
1  국가2  1059  184  267   86
2  국가3  1129  168  261   50
3  국가4   692  106  214  125
4  국가5  1335  296  296   84

In [16]:
df['방문객합계'] = df[['관광', '공무', '사업', '기타']].sum(axis=1)
df['관광객비율'] = df['관광']/ df['방문객합계']
df

       나라    관광   공무   사업   기타  방문객합계     관광객비율
0     국가1  1184  270  380   55   1889  0.626787
1     국가2  1059  184  267   86   1596  0.663534
2     국가3  1129  168  261   50   1608  0.702114
3     국가4   692  106  214  125   1137  0.608619
4     국가5  1335  296  296   84   2011  0.663849
..    ...   ...  ...  ...  ...    ...       ...
95   국가96   898  119  244  132   1393  0.644652
96   국가97  1111  195  234  118   1658  0.670084
97   국가98  1065  172  362   72   1671  0.637343
98   국가99  1408  254  288  149   2099  0.670796
99  국가100  1133  294  233  133   1793  0.631902

[100 rows x 7 columns]

In [18]:
res_1 = df.sort_values(by='관광객비율', ascending=False)
res_1

      나라    관광   공무   사업   기타  방문객합계     관광객비율
88  국가89  1370  103  227   75   1775  0.771831
84  국가85  1499  130  203  114   1946  0.770298
85  국가86  1437  124  231  125   1917  0.749609
30  국가31  1277  136  231   62   1706  0.748535
50  국가51  1461  198  203   96   1958  0.746170
..   ...   ...  ...  ...  ...    ...       ...
22  국가23   587  263  317   79   1246  0.471108
23  국가24   674  292  389   83   1438  0.468707
29  국가30   572  278  270  119   1239  0.461663
78  국가79   542  274  241  121   1178  0.460102
8    국가9   509  200  286  112   1107  0.459801

[100 rows x 7 columns]

In [19]:
res_1 = df.sort_values(by='관광객비율', ascending=False).iloc[1]['사업']
res_2 = df.sort_values(by='관광', ascending=False).iloc[1]['공무']
print(res_1, res_2)

203 238

In [21]:
# 2) 조건에 맞는 값 찾기
res_1 = df.nlargest(2, '관광객비율').iloc[1]['사업']
res_2 = df.nlargest(2, '관광').iloc[1]['공무']
print(res_1, res_2)

203 238

### 문2-2)